server:  
   port: 8081     
   servlet: 
      context-path: /basic
      session:
        timeout: 30m
api:
  info:
    title: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    terms-of-service: http://swagger.io/terms/
    contact:
      name: Gobithasan
      email: gobithasanhw@gmail.com
      url: http://gobithasan.com/team
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
  logging:
    enabled: true
    url-patterns: "/*"
        